volumes:
    langgraph-data:
        driver: local

services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 1s
            retries: 5

    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s

    langgraph-api:
        image: underdogquality23/maui:v1.0
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            DATABASE_URI: postgresql://postgres:postgres@langgraph-postgres:5432/postgres
