volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        image: "arbitrary"
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            PINECONE_API_KEY: "ef75d4e7-b787-41fe-8a58-0b2ab2b13a51"
            OPENAI_API_KEY: "sk-jN-7O_37tPiCKRgWhCh0jfCfobnRQpydZXruH3dWSTT3BlbkFJ2OAEIg6JHflcnE5OzEuD7OBwD_o2y6D0otjgN-R0EA"
            LANGSMITH_API_KEY: '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'
            TAVILY_API_KEY: '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'
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
